name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy application
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            APP_DIR=/home/ubuntu/nginx-rotate-app

            if [ ! -d "$APP_DIR/.git" ]; then
              git clone https://github.com/bvsrujan02-a11y/nginx-rotate-app.git $APP_DIR
            fi

            cd $APP_DIR

            git fetch origin
            git reset --hard origin/main

            docker compose down

            docker compose up --build -d

            docker image prune -f
